const COMMUNITIES_DETAILS_ACTION_SHARE = 1;
const COMMUNITIES_DETAILS_ACTION_TITLE_SHARE = 'Share';

const COMMUNITIES_DETAILS_ACTION_DELETE = 2;
const COMMUNITIES_DETAILS_ACTION_TITLE_DELETE = 'Delete';

const COMMUNITIES_DETAILS_ACTION_REPORT = 3;
const COMMUNITIES_DETAILS_ACTION_TITLE_REPORT = 'Report Post';

const COMMUNITIES_DETAILS_ACTION_EDIT = 4;
const COMMUNITIES_DETAILS_ACTION_TITLE_EDIT = 'Edit';

const ActionOptionType = {
  share: COMMUNITIES_DETAILS_ACTION_SHARE,
  delete: COMMUNITIES_DETAILS_ACTION_DELETE,
  report: COMMUNITIES_DETAILS_ACTION_REPORT,
  edit: COMMUNITIES_DETAILS_ACTION_EDIT,
};

const ActionOptions_SELF = [
  {
    title: COMMUNITIES_DETAILS_ACTION_TITLE_SHARE,
    value: COMMUNITIES_DETAILS_ACTION_SHARE,
  },
  {
    title: COMMUNITIES_DETAILS_ACTION_TITLE_EDIT,
    value: COMMUNITIES_DETAILS_ACTION_EDIT,
  },
  {
    title: COMMUNITIES_DETAILS_ACTION_TITLE_DELETE,
    value: COMMUNITIES_DETAILS_ACTION_DELETE,
  },
];

const ActionOptions_OTHERS = [
  {
    title: COMMUNITIES_DETAILS_ACTION_TITLE_SHARE,
    value: COMMUNITIES_DETAILS_ACTION_SHARE,
  },
  {
    title: COMMUNITIES_DETAILS_ACTION_TITLE_REPORT,
    value: COMMUNITIES_DETAILS_ACTION_REPORT,
  },
];

const DetailActionOptionsConstant = {
  actionOptionType: ActionOptionType,
  actionOptionsForOwnPost: ActionOptions_SELF,
  actionOptionsForOtherPost: ActionOptions_OTHERS,
};

export {DetailActionOptionsConstant};
