package sg.searchhouse.agentconnect.constant

object SharedPreferenceKey {

    const val PREF_COOKIE = "PREF_COOKIE"

    const val PREF_WHICH_SERVER = "PREF_WHICH_SERVER"
    const val PREF_CURRENT_USER = "PREF_CURRENT_USER"
    const val PREF_STREET_SINE_USER = "PREF_STREET_SINE_USER"

    const val PREF_SHOW_SPLASH_SCREEN = "PREF_SHOW_SPLASH_SCREEN"

    const val PREF_SEARCH_HISTORY_LISTINGS = "PREF_SEARCH_HISTORY_LISTINGS"
    const val PREF_SEARCH_HISTORY_TRANSACTIONS = "PREF_SEARCH_HISTORY_TRANSACTIONS"
    const val PREF_SEARCH_HISTORY_PROJECTS = "PREF_SEARCH_HISTORY_PROJECTS"
    const val PREF_SEARCH_HISTORY_NEW_LAUNCHES_REPORTS = "PREF_SEARCH_HISTORY_NEW_LAUNCHES_REPORTS"

    const val PREF_ENCRYPTED_SHARED_PREFERENCES = "PREF_ENCRYPTED_SHARED_PREFERENCES"

    const val PREF_LISTING_MANAGEMENT_PORTAL_MODE = "PREF_LISTING_MANAGEMENT_PORTAL_MODE"
    const val PREF_LISTING_MANAGEMENT_PORTAL_REMEMBER_ME =
        "PREF_LISTING_MANAGEMENT_PORTAL_REMEMBER_ME"
    const val PREF_LISTING_MANAGEMENT_PORTAL_EMAIL = "PREF_LISTING_MANAGEMENT_PORTAL_EMAIL"
    const val PREF_LISTING_MANAGEMENT_PORTAL_PASSWORD = "PREF_LISTING_MANAGEMENT_PORTAL_PASSWORD"

    //Server
    const val PREF_DEBUG_BASE_SERVER_URL = "PREF_DEBUG_BASE_SERVER_URL"
    const val PREF_STREET_SINE_USER_EMAIL = "PREF_STREET_SINE_USER_EMAIL"
    const val PREF_STREET_SINE_USER_PASSWORD = "PREF_STREET_SINE_USER_PASSWORD"

    const val PREF_EXISTING_HOME_REPORTS = "PREF_EXISTING_HOME_REPORTS"

    const val PREF_USER_SUBSCRIPTION_CONFIG = "PREF_USER_SUBSCRIPTION_CONFIG"

    // Transactions table swipe indicator
    const val PREF_IS_GROUP_TRANSACTIONS_SWIPE_INDICATOR_DISPLAYED =
        "PREF_IS_GROUP_TRANSACTIONS_SWIPE_INDICATOR_DISPLAYED"
    const val PREF_IS_PROJECT_TRANSACTIONS_SWIPE_INDICATOR_DISPLAYED =
        "PREF_IS_PROJECT_TRANSACTIONS_SWIPE_INDICATOR_DISPLAYED"

    // Watchlist
    const val PREF_SHOULD_REFRESH_DASHBOARD_LISTINGS_WATCHLIST =
        "PREF_SHOULD_REFRESH_DASHBOARD_LISTINGS_WATCHLIST"
    const val PREF_SHOULD_REFRESH_DASHBOARD_TRANSACTIONS_WATCHLIST =
        "PREF_SHOULD_REFRESH_DASHBOARD_TRANSACTIONS_WATCHLIST"

    const val PREF_AUTO_IMPORT_LISTINGS_DIALOG_FLAG = "PREF_AUTO_IMPORT_LISTINGS_DIALOG_FLAG"
}