package sg.searchhouse.agentconnect.event.transaction

import sg.searchhouse.agentconnect.model.api.transaction.ProjectTransactionRequest

class RequestLoadProjectTransactionsEvent(val projectTransactionRequest: ProjectTransactionRequest)